app_name: erpnext_theme
app_title: ERPNext Theme
app_description: Custom ERPNext theme inspired by modern design
app_author: 
app_email: 
app_icon: 
app_color: 
app_license: MIT
app_version: 0.0.1
app_depends:
depends_on:
  - frappe
  - erpnext